version: "3.9"

services:
  db:
    image: postgres:15.0-alpine
    container_name: db
    env_file:
      - ./environments/dev.env
    restart: unless-stopped
    environment:
      - POSTGRES_DB=currency_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - ./environments/dev.env
    environment:
      TARGET: api
      ENVIRONMENT: development
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
