from enum import Enum


class Message(Enum):
    # currency
    CURRENCY_ALREADY_EXISTS = "CURRENCY_ALREADY_EXISTS"
    CURRENCY_NOT_FOUND = "CURRENCY_NOT_FOUND"
    CURRENCY_CONVERT_INCONSISTENT_ERROR = "CURRENCY_CONVERT_INCONSISTENT_ERROR"
