"""

Revision ID: 8d7c6b0b03b7
Revises:
Create Date: 2022-10-20 21:17:58.423056

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8d7c6b0b03b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencies")
    # ### end Alembic commands ###
